# Лабораторне заняття №2
Знайомство з бібліотекою **NumPy**.

In [1]:
import numpy as np

## 1 Огляд функцій випадкового вибору

### 1.1 Функція *choice*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.choice.html).

In [2]:
a = ["top", 2, "bottom", 4.5]
size = 10
probs = [0.4, 0.2, 0.1, 0.3]
replace = True
print(np.random.choice(a, size=size, replace=replace, p=probs))

['4.5' 'top' 'top' 'top' 'top' '2' '2' 'top' '2' '4.5']


Згенеруйте одну випадкову цифру, вважаючи їх рівноймовірними.

In [5]:
print(np.random.choice(list(range(10))))

6

Згенеруйте випадкову матрицю $4 \times 6$ із рівноймовірних цифр.

In [9]:
print(np.random.choice(list(range(10)), size=(4, 6)))

[[0 6 3 0 2 0]
 [1 1 1 7 1 4]
 [4 9 2 0 5 1]
 [3 9 3 5 7 1]]


### 1.2 Функція *randint*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.randint.html).

In [8]:
low = 0
high = 5
size = 10
print(np.random.randint(low=low, high=high, size=size))

[1 2 0 2 3 4 3 1 3 4]


Згенеруйте одну випадкову цифру.

In [35]:
print(np.random.randint(low=0, high=10))

0


Згенеруйте випадкову матрицю $4 \times 5$ із двоцифрових чисел.

In [36]:
print(np.random.randint(low=10, high=100, size=(4, 5)))

[[10 36 71 86 12]
 [79 81 36 18 71]
 [46 60 53 33 88]
 [68 41 97 61 71]]


### 1.3 Функція *sample*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.sample.html).

In [12]:
size = None
print(np.random.sample(size=size))

0.2188262757964119


Згенеруйте випадкову матрицю $3 \times 4$ із чисел з інтервалу $[0, 1)$.

In [13]:
print(np.random.sample(size=(3, 4)))

[[0.80087404 0.58332044 0.45160849 0.11113887]
 [0.8633855  0.74666859 0.52629619 0.5126615 ]
 [0.8398362  0.14844309 0.92331447 0.63094193]]


Згенеруйте 10 випадкових чисел з інтервалу $[a, b)$.

In [10]:
a = 3
b = 5

In [14]:
print(np.random.sample(size=10))

[0.72053826 0.11673328 0.37156688 0.84755483 0.76863121 0.05420746
 0.01418261 0.95014268 0.84412076 0.05341377]


### 1.4 Функція *shuffle*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.shuffle.html).

In [16]:
x = np.arange(10)
np.random.shuffle(x)
print(x)

[5 7 8 2 0 3 9 1 6 4]


Перетасуйте матрицю $M$.

In [21]:
M = np.arange(20).reshape((4, 5))
print(M)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [22]:
np.random.shuffle(M)
print(M)

[[10 11 12 13 14]
 [ 5  6  7  8  9]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


In [23]:
# або 
M = M.flatten()
np.random.shuffle(M)
M = M.reshape((4, 5))
print(M)

[[18  0 16  9 19]
 [14  5 15 10  8]
 [ 4  2 17  7 11]
 [12 13  3  6  1]]


## 2 Відтворюваність результатів
Можна задати початкове значення для генератора. Це зафіксує "випадкову" послідовність.

In [24]:
np.random.seed(42)

In [25]:
print(np.random.randint(10))

6


In [26]:
print(np.random.randint(10))

3


In [27]:
np.random.seed(42)
print(np.random.randint(10))
print(np.random.randint(10))

6
3


In [28]:
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))

[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']
[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']


## 3 Монетка

### 3.1 За допомогою функції *choice*

In [29]:
p=0.5
n=10
tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
print(tosses)

['H' 'H' 'H' 'H' 'T' 'H' 'H' 'T' 'H' 'H']


In [30]:
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

8 heads and 2 tails


Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [31]:
p=0.5
n=100
tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
heads = list(tosses).count("H")
tails = list(tosses).count("T")
print("{} heads and {} tails".format(heads,tails))

50 heads and 50 tails


### 3.2 За допомогою функції *randint*
Реалізуйте симуляцію підкидань монетки за допомогою функції **randint**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [37]:
n = 100
tosses = np.random.randint(low=0, high=2, size=n)
heads = list(tosses).count(1)
tails = list(tosses).count(0)
print("{} heads and {} tails".format(heads,tails))


52 heads and 48 tails


### 3.3 За допомогою функції *sample*
Реалізуйте симуляцію підкидань монетки за допомогою функції **sample**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [40]:
n = 100
tosses = np.random.sample(size=n)
heads = tosses[tosses >= 0.5]
tails = tosses[tosses < 0.5]
print("{} heads and {} tails".format(len(heads), len(tails)))


54 heads and 46 tails


### 3.4 Задача
Знайдіть емпіричну ймовірність герба у симуляціях підкидання монетки $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [49]:
for n in (10,50,100,250,500,1000,2500,5000,10000):
    tosses = np.random.randint(low=0, high=2, size=n)
    heads = list(tosses).count(1) # Герб
    tails = list(tosses).count(0)
    print("For n = {} probability of Head is {}".format(n,heads/n))

For n = 10 probability of Head is 0.3
For n = 50 probability of Head is 0.54
For n = 100 probability of Head is 0.48
For n = 250 probability of Head is 0.464
For n = 500 probability of Head is 0.496
For n = 1000 probability of Head is 0.478
For n = 2500 probability of Head is 0.508
For n = 5000 probability of Head is 0.5092
For n = 10000 probability of Head is 0.4969


## 4 Гральний кубик
### 4.1 Реалізація симуляцій
Реалізуйте симуляцію кидків грального кубика за допомогою функції **???**. Просимулюйте $60$ кидків кубика та підрахуйте кількість кожної із сторін.

In [54]:
sides = tuple(range(1, 7))
n = 60
tosses = np.random.randint(low=1, high=7, size=n)
for side in sides:
    print("For side {} got {} flips.".format(side, list(tosses).count(side)))

For side 1 got 5 flips.
For side 2 got 16 flips.
For side 3 got 7 flips.
For side 4 got 11 flips.
For side 5 got 10 flips.
For side 6 got 11 flips.


### 4.2 Задача
Знайдіть емпіричну ймовірність кожної сторони у симуляціях кидання грального кубика $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [55]:
for n in (10,50,100,250,500,1000,2500,5000,10000):
    print("N =", n)
    tosses = np.random.randint(low=1, high=7, size=n)
    for side in sides:
        print("\tFor side {} probability is {}.".format(side, list(tosses).count(side)/n))

N = 10
	For side 1 probability is 0.0.
	For side 2 probability is 0.2.
	For side 3 probability is 0.2.
	For side 4 probability is 0.1.
	For side 5 probability is 0.3.
	For side 6 probability is 0.2.
N = 50
	For side 1 probability is 0.18.
	For side 2 probability is 0.18.
	For side 3 probability is 0.18.
	For side 4 probability is 0.2.
	For side 5 probability is 0.1.
	For side 6 probability is 0.16.
N = 100
	For side 1 probability is 0.23.
	For side 2 probability is 0.18.
	For side 3 probability is 0.16.
	For side 4 probability is 0.11.
	For side 5 probability is 0.14.
	For side 6 probability is 0.18.
N = 250
	For side 1 probability is 0.124.
	For side 2 probability is 0.16.
	For side 3 probability is 0.136.
	For side 4 probability is 0.192.
	For side 5 probability is 0.172.
	For side 6 probability is 0.216.
N = 500
	For side 1 probability is 0.16.
	For side 2 probability is 0.152.
	For side 3 probability is 0.196.
	For side 4 probability is 0.17.
	For side 5 probability is 0.15.
	For s

## 5 Колода карт
### 5.1 Реалізація

In [59]:
# Визначимо номінали, масті та карти
Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
Suits = {'♢', '♠', '♣', '♡'}
# Створимо колоду карт
Cards = sorted([(Rank, Suit) for Rank in Ranks for Suit in Suits])
print(Cards)

[('1', '♠'), ('1', '♡'), ('1', '♢'), ('1', '♣'), ('10', '♠'), ('10', '♡'), ('10', '♢'), ('10', '♣'), ('2', '♠'), ('2', '♡'), ('2', '♢'), ('2', '♣'), ('3', '♠'), ('3', '♡'), ('3', '♢'), ('3', '♣'), ('4', '♠'), ('4', '♡'), ('4', '♢'), ('4', '♣'), ('5', '♠'), ('5', '♡'), ('5', '♢'), ('5', '♣'), ('6', '♠'), ('6', '♡'), ('6', '♢'), ('6', '♣'), ('7', '♠'), ('7', '♡'), ('7', '♢'), ('7', '♣'), ('8', '♠'), ('8', '♡'), ('8', '♢'), ('8', '♣'), ('9', '♠'), ('9', '♡'), ('9', '♢'), ('9', '♣'), ('J', '♠'), ('J', '♡'), ('J', '♢'), ('J', '♣'), ('K', '♠'), ('K', '♡'), ('K', '♢'), ('K', '♣'), ('Q', '♠'), ('Q', '♡'), ('Q', '♢'), ('Q', '♣')]


In [60]:
# Інший вівід результату
print(', '.join([(card[0] + card[1]) for card in Cards]))

1♠, 1♡, 1♢, 1♣, 10♠, 10♡, 10♢, 10♣, 2♠, 2♡, 2♢, 2♣, 3♠, 3♡, 3♢, 3♣, 4♠, 4♡, 4♢, 4♣, 5♠, 5♡, 5♢, 5♣, 6♠, 6♡, 6♢, 6♣, 7♠, 7♡, 7♢, 7♣, 8♠, 8♡, 8♢, 8♣, 9♠, 9♡, 9♢, 9♣, J♠, J♡, J♢, J♣, K♠, K♡, K♢, K♣, Q♠, Q♡, Q♢, Q♣


In [61]:
# Або згрупувавши по мастях
for suit in Suits:
    print(", ".join([(suit+rank) for rank in Ranks]))

♣10, ♣5, ♣K, ♣9, ♣4, ♣8, ♣2, ♣6, ♣3, ♣J, ♣Q, ♣1, ♣7
♠10, ♠5, ♠K, ♠9, ♠4, ♠8, ♠2, ♠6, ♠3, ♠J, ♠Q, ♠1, ♠7
♢10, ♢5, ♢K, ♢9, ♢4, ♢8, ♢2, ♢6, ♢3, ♢J, ♢Q, ♢1, ♢7
♡10, ♡5, ♡K, ♡9, ♡4, ♡8, ♡2, ♡6, ♡3, ♡J, ♡Q, ♡1, ♡7


In [62]:
# Перемішаємо колоду
np.random.shuffle(Cards)

print(Cards)

[('4', '♣'), ('Q', '♡'), ('10', '♠'), ('K', '♣'), ('8', '♣'), ('J', '♠'), ('9', '♠'), ('10', '♣'), ('J', '♣'), ('8', '♢'), ('2', '♣'), ('8', '♡'), ('4', '♢'), ('10', '♡'), ('Q', '♠'), ('Q', '♢'), ('5', '♡'), ('K', '♢'), ('7', '♠'), ('3', '♡'), ('3', '♠'), ('1', '♡'), ('Q', '♣'), ('1', '♣'), ('3', '♢'), ('5', '♣'), ('1', '♢'), ('7', '♣'), ('J', '♢'), ('5', '♠'), ('9', '♣'), ('3', '♣'), ('K', '♡'), ('5', '♢'), ('6', '♣'), ('2', '♠'), ('4', '♡'), ('6', '♡'), ('J', '♡'), ('9', '♡'), ('6', '♢'), ('7', '♢'), ('7', '♡'), ('8', '♠'), ('4', '♠'), ('10', '♢'), ('1', '♠'), ('K', '♠'), ('2', '♡'), ('9', '♢'), ('6', '♠'), ('2', '♢')]


### 5.2 Задача
Знайдіть емпіричну ймовірність карти парного числа (2, 4, 6, 8, 10) у симуляціях вибору однієї карти з колоди 52 карт $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [98]:
def check(a):
    target = ['2', '4', '6', '8', '10']
    return a[0] in target
cards = np.array(Cards)
for n in (10,50,100,250,500,1000,2500,5000,10000):
    choices = np.random.choice(list(range(len(Cards))), size=n)
    sad = cards[choices]
    sad = sad[np.apply_along_axis(check, 1, sad)]
    print('For n = {} probability of showing card with even number is {}'.format(n, len(sad)/n))

For n = 10 probability of showing card with even number is 0.1
For n = 50 probability of showing card with even number is 0.44
For n = 100 probability of showing card with even number is 0.42
For n = 250 probability of showing card with even number is 0.368
For n = 500 probability of showing card with even number is 0.384
For n = 1000 probability of showing card with even number is 0.397
For n = 2500 probability of showing card with even number is 0.3912
For n = 5000 probability of showing card with even number is 0.3742
For n = 10000 probability of showing card with even number is 0.3799


### 5.3 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав 4 карти однієї масті та по 3 карти інших мастей. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♢7, ♢K, ♡9, ♡1, ♡5}.

In [ ]:
from itertools import cycle

list(cycle([1, 2, 3]))

In [116]:

hands = list()
suits = list(Suits)
ranks = list(Ranks)
np.random.shuffle(suits)
np.random.shuffle(ranks)
for suit in suits:
    for j in (4, 3, 3, 3):
        

['♣', '♠', '♢', '♡']
['♠', '♡', '♣', '♢']


### 5.4 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав від 2 до 5 карт кожної масті. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♣7, ♢K, ♡9, ♡1, ♡5}.

In [36]:
# Місце для Вашого коду

